DROP TABLE EVNT_LOG IF EXISTS;

CREATE TABLE EVNT_LOG  (
    EVNT_ID VARCHAR(20) NOT NULL PRIMARY KEY,
    EVNT_TYPE VARCHAR(8) NULL,
    EVNT_HOST VARCHAR(20) NULL,
    EVNT_ALRT VARCHAR(5),
    EVNT_DURATION BIGINT 
);